export default {
	state: {
		SELECT_DOMAINS: 'SELECT_DOMAINS',
		MODE_MULTIPLE: 'MODE_MULTIPLE'
	},
	mutations: {
		SET_LIST_SELECT_DOMAINS: 'SET_LIST_SELECT_DOMAINS',
		SET_MODE_MULTIPLE: 'SET_MODE_MULTIPLE'
	}
};
