export default {
	state: {
		VISIBILITY: 'VISIBILITY',
		TABLE_SCHEME: 'TABLE_SCHEME',
		LINK_ON_ELEMENT: 'LINK_ON_ELEMENT',
		FIELD_ID: 'FIELD_ID'
	},
	mutations: {
		SET_VISIBILITY: 'SET_VISIBILITY',
		SET_TABLE_SCHEME: 'SET_TABLE_SCHEME',
		SET_LINK_ON_ELEMENT: 'SET_LINK_ON_ELEMENT',
		SET_FIELD_ID: 'SET_FIELD_ID'
	},
	actions: {
		SHOW_ADD_CONTENT: 'SHOW_ADD_CONTENT',
		HIDE_ADD_CONTENT: 'HIDE_ADD_CONTENT',
		ADD_LINK: 'ADD_LINK'
	}
};
